sudo: required
services:
    - docker

before_install:
    - docker build -t patryckpabllo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true patryckpabllo/docker-react npm run test
